# -*- coding: utf-8 -*-
# @Time : 2019/4/1
# @Author : zxy

CONCURRENCY_NUM = 5
MAX_RETRY_TIMES = 3
USE_PROXY = False

DEFAULT_DB_CONFIG = {
    'host': '127.0.0.1',
    'port': '27017',
    'db_name': 'House365',
    'user': 'root',
    'passwd': 'csdjgs9B15BS',
    'auth_db': 'admin'
}

COLLECTION_SHPersonalHouse = 'SHPersonalHouse'

LOG_BASE_NAME = 'house365'

# 二手可用城市
SH_AVAILABLE_CITIES = [
    'nj',
    'sz',
    'wx',
    'cz',
    'hf',
    'hz',
    'xa',
    'cq',
    'sy',
    'nt',
    'tz',
    'tj',
    'xz',
    'yz',
    'bb',
    'jx',
    'cd',
    'hrb',
    'chuzhou',
    'mas',
    'bd',
    'fy',
    'zunyi',
    'jr',
    'lz',
    'lyg',
    'la',
    'xx',
    'zj',
    'ty',
    'yc',
    'hy',
    'dy',
    'mianyang',
    'hn',
    'wlmq',
    'sh',
    'bh',
    'nc',
    'fcg',
    'aq',
    'tl',
    'xc',
    'wh']

# 特殊城市，需要使用其他方法来获取最大页码
SPECIAL_CITIES = ['wh']

# 最大页码清洗类型 针对最大页码text是min/max格式的数据进行清洗
MAX_PAGE_CLEAN_TYPE = [
    'cz_max_page',
    'sz_max_page',
    'hz_max_page',
    'xa_max_page',
    'sy_max_page',
    'tz_max_page',
    'tj_max_page',
    'xz_max_page',
    'yz_max_page',
    'cd_max_page',
    'hrb_max_page',
    'chuzhou_max_page',
    'mas_max_page',
    'fy_max_page',
    'zunyi_max_page',
    'jr_max_page',
    'lz_max_page',
    'la_max_page',
    'xx_max_page',
    'zj_max_page',
    'yc_max_page',
    'hy_max_page',
    'dy_max_page',
    'hn_max_page']


CITIES_DICT = {
    'nj': '南京',
    'sz': '苏州',
    'ks': '昆山',
    'wx': '无锡',
    'cz': '常州',
    'hf': '合肥',
    'wh': '芜湖',
    'hz': '杭州',
    'xa': '西安',
    'cq': '重庆',
    'sy': '沈阳',
    'hb': '淮北',
    'nt': '南通',
    'tz': '泰州',
    'tj': '天津',
    'xz': '徐州',
    'yz': '扬州',
    'yx': '宜兴',
    'bb': '蚌埠',
    'jx': '嘉兴',
    'cc': '长春',
    'cd': '成都',
    'wz': '温州',
    'hrb': '哈尔滨',
    'sjz': '石家庄',
    'jinan': '济南',
    'suzhou': '宿州',
    'wuhan': '武汉',
    'chuzhou': '滁州',
    'fuling': '涪陵',
    'hs': '衡水',
    'jieyang': '揭阳',
    'chaozhou': '潮州',
    'st': '汕头',
    'mas': '马鞍山',
    'ly': '临沂',
    'zhuzhou': '株洲',
    'dz': '德州',
    'jining': '济宁',
    'bd': '保定',
    'nb': '宁波',
    'zh': '珠海',
    'zs': '中山',
    'dl': '大连',
    'fy': '阜阳',
    'jh': '金华',
    'hd': '邯郸',
    'zunyi': '遵义',
    'jr': '句容',
    'lz': '兰州',
    'lh': '六合',
    'qz': '泉州',
    'km': '昆明',
    'enshi': '恩施',
    'sx': '绍兴',
    'ls': '溧水',
    'zz': '郑州',
    'lyg': '连云港',
    'zaozhuang': '枣庄',
    'gc': '高淳',
    'yt': '烟台',
    'la': '六安',
    'xx': '新乡',
    'jy': '江阴',
    'fjzz': '漳州',
    'cs': '常熟',
    'xt': '邢台',
    'zj': '镇江',
    'huaian': '淮安',
    'qd': '青岛',
    'ty': '太原',
    'jz': '晋中',
    'zq': '肇庆',
    'yf': '云浮',
    'yc': '盐城',
    'taizhou': '台州',
    'hy': '海盐',
    'lf': '廊坊',
    'yy': '岳阳',
    'dy': '东营',
    'mianyang': '绵阳',
    'hn': '海宁',
    'wlmq': '乌鲁木齐',
    'ph': '平湖',
    'tx': '桐乡',
    'gy': '贵阳',
    'sh': '上海',
    'bh': '北海',
    'nc': '南昌',
    'fcg': '防城港',
    'aq': '安庆',
    'tl': '铜陵',
    'xc': '宣城'}
